//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forshc
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public int idUsers { get; set; }
        public int idChest { get; set; }
        public System.DateTime dateaddr { get; set; }
        public int count { get; set; }
    
        public virtual Chest Chest { get; set; }
        public virtual Users Users { get; set; }
    }
}
